version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "FSharp.Core"
        update-types: [ "version-update:semver-minor", "version-update:semver-patch" ]
    groups:
      deps:
        patterns: [ "*" ]