trigger: none
pr: none

resources:
  pipelines:
    - pipeline: build
      source: 'Build'
      trigger: true

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: functions
    displayName: 'Functions'
    type: stringList
    values:
      - mp4towebm
      - removesound
      - webmtomp4
    default:
      - mp4towebm
      - removesound
      - webmtomp4

stages:
  - stage: deploy_dev
    displayName: 'Deploy DEV'
    jobs:
      - deployment: deploy_dev
        displayName: Deploy DEV
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: build
                  artifact: drop

                - ${{ each function in parameters.functions }}:
                    - task: AzureFunctionApp@2
                      displayName: 'Deploy ${{ function }}'
                      inputs:
                        azureSubscription: 'az-dev-${{ function }}'
                        appType: 'functionAppLinux'
                        appName: 'func-${{ function }}-tg-bot-dev'
                        package: '$(Pipeline.Workspace)/**/*.zip'
  - stage: deploy_prd
    displayName: 'Deploy PRD'
    trigger: manual
    jobs:
      - deployment: deploy_prd
        displayName: Deploy PRD
        environment: 'prd'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: build
                  artifact: drop

                - ${{ each function in parameters.functions }}:
                    - task: AzureFunctionApp@2
                      displayName: 'Deploy ${{ function }}'
                      inputs:
                        azureSubscription: 'az-prd-${{ function }}'
                        appType: 'functionAppLinux'
                        appName: 'func-${{ function }}-tg-bot-prd'
                        package: '$(Pipeline.Workspace)/**/*.zip'
